import React from "react"; // Import React
import type { Metadata } from "next";
import "./globals.css";
import Providers from "../providers/Providers";
import { Inter } from "next/font/google";
import { Session } from "@/lib/types";
import { cn } from "@/lib/utils";
import SideNavBar from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Posts Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: Session;
}): JSX.Element {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen w-full bg-white text-black flex",
          inter.className,
          {
            "debug-screens": process.env.NODE_ENV === "development",
          },
        )}
      >
        <Providers session={session}>
          <SideNavBar />
          <div className="flex-1 ml-[var(--sidebar-width)] p-8 overflow-y-auto">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
